### ISSUE TITLE
Error with Spyder IPython Shell - AttributeError: 'NoneType' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by shahrukhkhan489** [spyder-ide/spyder-kernels#191] opened 2019-12-22 15:55 UTC
This issue is on MacOS. Have checked [Issue #8668](https://github.com/spyder-ide/spyder/issues/8668), and the [pull request fix](https://github.com/spyder-ide/spyder-kernels/commit/e3847f1d167a49b35d1307db21ad57fb868d34c5) seems to be there.

```IPython 7.8.0 -- An enhanced Interactive Python.
Error in callback <function sys_pipes_forever at 0x11a3477a0> (for pre_execute):
Traceback (most recent call last):

  File "/Users/skhan/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 331, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/Users/skhan/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/Users/skhan/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 298, in pipes
    with w:

  File "/Users/skhan/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 151, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/Users/skhan/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 100, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'```

Have taken a reference from https://github.com/spyder-ide/spyder-kernels/commit/e3847f1d167a49b35d1307db21ad57fb868d34c5

**Comment by ccordoba12** [comment] 2019-12-23 00:05
I think this is fixed in the latest `wurlitzer` version. Please update it and try again.

**Comment by ncneal** [comment] 2020-01-30 14:47
I just updated to Spyder 4 and am getting the following on MacOS:
`Error in callback <function sys_pipes_forever at 0x11f1f2048> (for pre_execute):
Traceback (most recent call last):

  File "/Users/nickneal/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 339, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/Users/nickneal/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/Users/nickneal/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 306, in pipes
    with w:

  File "/Users/nickneal/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 158, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/Users/nickneal/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 107, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'`

I have the latest `wurlitzer` version but am still getting this message anytime I use the console.

**Comment by ccordoba12** [comment] 2020-01-30 20:43
@impact27, could you help us with this one? We could simply catch the error and print an informative message about it.

**Comment by impact27** [comment] 2020-01-31 07:28
I don't think this touches spyder code, so I'm not sure where we could catch that. We should open an issue on https://github.com/minrk/wurlitzer. Do you have a way of reproducing the error?

**Comment by impact27** [comment] 2020-01-31 08:51
Do you have code that sets `sys.__stdout__` to None? This shouln't happen.

**Comment by impact27** [comment] 2020-01-31 08:56
I opened https://github.com/minrk/wurlitzer/issues/36

**Comment by ccordoba12** [comment] 2020-01-31 15:32
Thanks @impact27!

**Comment by muhlbach** [comment] 2020-02-13 14:24
I'm experiencing the same issue with `wurlitzer=2.0.0`, `spyder=4.0.1` and `python=3.7.0`. I'm running macOS 10.15.3. Any updates or fixes?

```
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.
Error in callback <function sys_pipes_forever at 0x11e652320> (for pre_execute):
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 339, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 306, in pipes
    with w:

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 158, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 107, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'


```

**Comment by impact27** [comment] 2020-02-13 14:33
@muhlback
Do you have any idea why `sys.__stdout__` is `None` in your case? Can you check if this is the case?

**Comment by muhlbach** [comment] 2020-02-13 14:37
@impact27:

Do you mean like this?
```

import sys

sys.__stdout__
Error in callback <function sys_pipes_forever at 0x119208320> (for pre_execute):
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 339, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 306, in pipes
    with w:

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 158, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 107, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by impact27** [comment] 2020-02-13 14:57
You can do:
```
import sys
print(str(sys.__stdout__))
```
I can reproduce this bug if I write (Which is probably not a good idea):
```
sys.__stdout__ = None
```

**Comment by impact27** [comment] 2020-02-13 14:58
So is this a bug you get on a used console that ran code that might have done `sys.__stdout__ = None` or do you get this on a new console?

**Comment by muhlbach** [comment] 2020-02-13 15:04
I confirm that this gives `None`:
```
import sys
print(str(sys.__stdout__))
Error in callback <function sys_pipes_forever at 0x12043a320> (for pre_execute):
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 339, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 306, in pipes
    with w:

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 158, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 107, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'

None
```

This happens when I start a new console.

**Comment by impact27** [comment] 2020-02-13 15:09
I don't really understand how this is possible:
 - What about `sys.stdout`?
 - Do you run any code on startup? (Preferences -> iPython console -> Stratup -> Run Code)
 - From https://docs.python.org/3.8/library/sys.html it is possible but we __are__ connected to a console:
> Note
> 
> Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.

**Comment by muhlbach** [comment] 2020-02-13 15:12
Also `None` when I print `sys.__stdout__`.

I don't run any code on start up:
![Screen Shot 2020-02-13 at 16 11 54](https://user-images.githubusercontent.com/31421850/74448667-a4242e80-4e7b-11ea-8442-a14ab2d2e73a.png)

**Comment by impact27** [comment] 2020-02-13 15:14
What about:
```
import sys
print(str(sys.__stdout__), str(sys.stdout), str(sys.__stderr__), str(sys.stderr))
```

**Comment by muhlbach** [comment] 2020-02-13 15:16
```

import sys
print(str(sys.__stdout__), str(sys.stdout), str(sys.__stderr__), str(sys.stderr))
Error in callback <function sys_pipes_forever at 0x11833a320> (for pre_execute):
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 339, in sys_pipes_forever
    _mighty_wurlitzer.__enter__()

  File "/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 306, in pipes
    with w:

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 158, in __enter__
    pipe = self._setup_pipe('stdout')

  File "/opt/anaconda3/lib/python3.7/site-packages/wurlitzer.py", line 107, in _setup_pipe
    real_fd = getattr(sys, '__%s__' % name).fileno()

AttributeError: 'NoneType' object has no attribute 'fileno'

None <ipykernel.iostream.OutStream object at 0x117dec150> <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> <ipykernel.iostream.OutStream object at 0x117dec0d0>
```

Btw thank you for your persistency!

**Comment by impact27** [comment] 2020-02-13 15:28
Check if you have the latest version of ipykernel maybe?
Workaround:
```
import sys; sys.__stdout__ = sys.__stderr__
```

**Comment by muhlbach** [comment] 2020-02-13 15:33
I'm running with `ipykernel=5.1.4 (py37h39e3cac_0)`, which should be the latest version.

**Comment by MichaelClerx** [comment] 2020-03-21 10:03
Any luck with debugging this? I'm getting a similar report from a user running my software (which contains a line involving `sys.__stdout__.fileno()` that now complains because `__stdout__` has been set to `None`)

**Comment by yotamcons** [comment] 2020-05-20 12:34
I have the same issue with spyder 3.3.6 and python 3.6 on macOS 10.15.4
it goes away if I exit Spyder and than reopen

**Comment by jmucla** [comment] 2020-05-26 06:40
I ran into the same error when calling Sypder3 from a bash shell (Python 3.7.4 IPython 7.14.0).  I noticed it was complaining about pipes, so I did the naive thing, invoked Spyder sending stdout and stderr to /dev/null e.g:

/usr/bin/spyder3 &>/dev/null &

and the problem seemed to go away.

**Comment by impact27** [comment] 2020-05-27 06:21
@ccordoba12 Should we disable wurlitzer if stdout is disabled?

**Comment by impact27** [comment] 2022-06-25 10:57
Fixed by https://github.com/minrk/wurlitzer/pull/44

**Comment by ccordoba12** [comment] 2022-07-06 14:22
Great! Closing this one then.

**Closed by ccordoba12** 2022-07-06 14:22 UTC
Labels: type:Bug
