### ISSUE TITLE
Spydata files won't import if the original filename is changed

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-kernels#9] opened 2018-07-17 16:09 UTC
@TinyCloud commented on [Tue Jul 17 2018](https://github.com/spyder-ide/spyder/issues/7483)

## Problem Description
Whenever I've saved a session's data as a .spydata file and tried to import it at a later point in time, the behavior is highly erratic - works sometimes and does not do anything sometimes.

### What steps will reproduce the problem?
- Export a copy of the session dataframes and variables by Save as from Variable explorer . Ex: test.spydata in your working directory.
- Use import from variable explorer to open the same file. Does not always work.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.6.0

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

---

@ccordoba12 commented on [Tue Jul 17 2018](https://github.com/spyder-ide/spyder/issues/7483#issuecomment-405638147)

Moving to the right repo.

**Comment by ccordoba12** [comment] 2018-07-17 16:11
@TinyCloud, we understand your frustration, but unfortunately this feature doesn't work well in Spyder 3. However, we plan to improve it for Spyder 4 so that it's much more reliable.

**Comment by TinyCloud** [comment] 2018-07-17 17:21
I understand. But for now, is there any way I could recover my variables
and dataframes from the .spydata file I have? That'd be really helpful
information.

Regards,
Anumeha

**Comment by ccordoba12** [comment] 2018-07-17 18:57
I think we run some verifications before trying to save your objects, so if they can't be recovered is because they couldn't be saved in the first place, sorry.

**Comment by TinyCloud** [comment] 2018-07-18 13:41
But it has the right size of 7GB still and opening in text editor shows
content inside (all kinds of hexadecimal entries though), which makes me
think that the data did get saved to the file so only I'm wondering if
there's still a way to recover it. Else, I'll work on my alternate plans.

Regards,

**Comment by CAM-Gerlach** [comment] 2018-08-06 09:46
@TinyCloud If you can share either the file or the exact error/traceback you're getting with us, its possible we could figure something out (assuming its a particular data structure that's causing it, we can basically have it skip over the data structure(s) its having a problem with and keep loading the rest). Basically, the medium-term fix is something like spyder-ide/spyder#7257 but at this point its unlikely to get implemented before Spyder 4, which has the real solution to the underlying problem in that its able to save many more types.

**Comment by PJ0190** [comment] 2019-01-10 15:42
Hello,
maybe a little bit late, but I had a similar problem. I saved the variables within spyder and could not open them again. The problem in my case was, that I saved the data in e.g. folder A. Renamed it afterwards and put it in folder B. There I could not open it with spyder. After I put it back in folder A and renamed it again so that it had the original name it was possible to open it in spyder.

best regards

**Comment by CAM-Gerlach** [comment] 2019-01-10 23:02
> The problem in my case was, that I saved the data in e.g. folder A. Renamed it afterwards and put it in folder B.

Thanks very much; I have been able to reproduce and isolate the behavior; it is specifically due to renaming the file in question (moving it doesn't affect whether it works), apparently due to a side effect of the original filename being included in the first line of the output file and evidently something checking against it when it apparently shouldn't.

@ccordoba12 Should I make a separate issue or should we simply rename this issue to ".spydata files won't open if renamed" or something, given the low likelihood of the OP returning and sharing their problematic file to determine whether or not this was the cause.

**Comment by ccordoba12** [comment] 2019-01-11 01:18
Please rename the issue.

**Comment by CAM-Gerlach** [comment] 2019-01-13 21:09
The problem turned out to be pretty simple; in ``load_dictionary()`` in ``spyder_kernels/utils/iofuncs.py``, it uses the current ``.spydata`` filename as the base name to iterate through the untarred files, which are named based on what the ``.spydata`` file was called original. Obviously, if these are different, it won't find any of the untarred files and they will not be loaded. The simplest way to fix this is to just extract the original filename by reading it in from the first line of the ``.spydata`` tar file, and then everything else should work normally.

**Comment by CAM-Gerlach** [comment] 2019-01-13 21:14
@ccordoba12 Can I just base against ``0.x`` since this is a non-trivial bug and there are no changes to the relevant file between ``0.x`` and ``master`` to cause merge issues?

**Closed** 2019-01-26 09:51 UTC
Labels: bug
